import { type Metadata } from "next"
import { type PropsWithChildren } from "react"
import { ServiceWorkerProvider } from "@/components/service-worker-provider"

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
}

const Layout: React.FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <ServiceWorkerProvider scriptURL="/service-worker.js">{children}</ServiceWorkerProvider>
      </body>
    </html>
  )
}

export default Layout
