import { type Metadata } from "next"
import { type PropsWithChildren } from "react"
import { PushNotification } from "@/components/push-notification"

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
}

const Layout: React.FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en">
      <body>
        {children}
        <PushNotification />
      </body>
    </html>
  )
}

export default Layout
