import { type Metadata } from "next"
import { type PropsWithChildren } from "react"
import ServiceWorker from "@/components/service-worker"

export const metadata: Metadata = {
  description: "Generated by create next app",
  title: "Create Next App",
}

const Layout: React.FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <ServiceWorker />
        {children}
      </body>
    </html>
  )
}

export default Layout
